service:
  name: teleport-dresser
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  stages:
    - local
    - dev
    - production
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dotenv:
    path: ./.env
    include:
      - FIREBASE_STORAGE_BUCKET

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: src/app.handler
    memorySize: 128
    timeout: 900
    events:
      - http: ANY /
      - http: ANY /{proxy+}
